apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect-application
  namespace: argocd
spec:
  destination:
    namespace: 1password-connect
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 2.3.0
    helm:
      releaseName: onepassword
      valuesObject:
        connect:
          credentialsName: op-connect-credentials
          credentialsKey: 1password-credentials.json
          serviceType: ClusterIP
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
