apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
      # Vikunja Container
      - image: vikunja/vikunja
        name: vikunja
        env:
        - name: VIKUNJA_SERVICE_PUBLICURL
          value: "https://todo.senk0.com"
        - name: VIKUNJA_DATABASE_HOST
          value: "localhost"  # Use localhost since both containers are in the same Pod
        - name: VIKUNJA_DATABASE_PASSWORD
          value: "changeme"
        - name: VIKUNJA_DATABASE_TYPE
          value: "mysql"
        - name: VIKUNJA_DATABASE_USER
          value: "vikunja"
        - name: VIKUNJA_DATABASE_DATABASE
          value: "vikunja"
        - name: VIKUNJA_SERVICE_JWTSECRET
          value: "a-super-secure-random-secret"  # Replace with a secure secret
        - name: VIKUNJA_CORS_ENABLE
          value: "true"
        volumeMounts:
        - name: files
          mountPath: /app/vikunja/files
        ports:
        - containerPort: 3456
        resources:
          limits:
            cpu: 1
            memory: 128Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
      - name: mariadb
        image: mariadb:10
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "supersecret"
        - name: MYSQL_USER
          value: "vikunja"
        - name: MYSQL_PASSWORD
          value: "changeme"
        - name: MYSQL_DATABASE
          value: "vikunja"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: vikunja-pvc
      - name: db-data
        persistentVolumeClaim:
          claimName: vikunja-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem