apiVersion: v1
kind: Service
metadata:
  name: pocket-id
  namespace: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/instance: pocket-id
    # renovate: image=ghcr.io/pocket-id/pocket-id
    app.kubernetes.io/version: "v2"
    app.kubernetes.io/component: sso-provider
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1411
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/instance: pocket-id
