apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttx
  labels:
    app: mqttx
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mqttx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqttx
    spec:
      serviceAccountName: the-pod-reader
      containers:
      - image: emqx/mqttx-web
        name: mqttx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 128Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
