apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privatebin-ingress
  namespace: privatebin
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: immich.batlab.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-application-server
            port:
              number: 2283