apiVersion: apps/v1 
kind: Deployment
metadata:
  name: valheim-vanilla
  labels:
    app: valheim-vanilla
spec:
  revisionHistoryLimit: 1
  replicas: 0
  selector:
    matchLabels:
      app: valheim-vanilla
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: valheim-vanilla
    spec:
      containers:
      - image: lloesche/valheim-server
        name: valheim-vanilla
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /opt/valheim
        ports:
        - containerPort: 2456
          protocol: UDP
        - containerPort: 2457
          protocol: UDP
        env: 
        - name: SERVER_NAME
          value: "Valin"
        - name: WORLD_NAME
          value: "owo"
        - name: SERVER_PUBLIC
          value: "true"
        - name: TZ
          value: "CST"
        resources:
          limits:
            cpu: 4
            memory: 4096Mi
            ephemeral-storage: 2Gi
          requests:
            cpu: 100m
            memory: 2048Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: valheim-vanilla-assets
          readOnly: false
      - name: data
        persistentVolumeClaim:
          claimName: valheim-vanilla-data
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-vanilla-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-vanilla-assets
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
