apiVersion: apps/v1 
kind: Deployment
metadata:
  name: planarally
  labels:
    app: planarally
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: planarally
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: planarally
    spec:
      containers:
      - image: kruptein/planarally
        name: planarally
        volumeMounts:
        - name: assets
          mountPath: /planarally/static/assets/
        - name: data
          mountPath: /planarally/data/
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 1
            memory: 64Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
      volumes:
      - name: assets
        persistentVolumeClaim:
          claimName: planarally-assets-pvc
          readOnly: false
      - name: data
        persistentVolumeClaim:
          claimName: planarally-data-pvc
          readOnly: false
      securityContext:
        fsGroup: 0
        runAsUser: 0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: planarally-assets-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: planarally-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
