apiVersion: v1
kind: Service
metadata:
  name: vikunja
  namespace: vikunja
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/service: vikunja
spec:
  type: ClusterIP
  ports:
    - port: 3456
      targetPort: 3456
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: vikunja
